name: Perfect Gold
description: Описание Магазина

# site url if it will live in project page
baseurl: /perfectgold
markdown: rdiscount
encoding: utf-8
pygments: true
paginate: 20
permalink: /:categories/:title
